import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Button } from "@/components/ui/button"
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div>
          <Button variant={'link'}> <Link href="/">Feed</Link></Button>
          <Button variant={'link'}> <Link href="/filter">filter</Link></Button>
          <Button variant={'link'}> <Link href="/search">search</Link></Button>
        </div>
        {/* Line spanning width with tailwind*/}
        <div className="h-0.5 bg-gray-300 m-4"></div>
        <div className='mx-4'>
          {children}
        </div>
      </body>

    </html>
  )
}
